# Generated by Django 4.2.6 on 2023-11-05 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя категории', max_length=255)),
                ('description', models.CharField(help_text='Описание категории', max_length=1024)),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания модели')),
                ('deliver_address', models.CharField(help_text='Адрес доставки заказа', max_length=255)),
                ('phone_number', models.CharField(error_messages='Номер телефона не является российским номером или же неправильно набран', max_length=11, validators=[django.core.validators.RegexValidator(regex='^((\\7|8)+([0-9]){10})$')])),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_products', models.PositiveIntegerField(default=0, help_text='Количество позиций в заказе')),
                ('discount_per_single_product', models.FloatField(default=0.0, help_text='Скидка за единицу товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.order')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиция заказа',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без названия', help_text='Имя продукта', max_length=255)),
                ('price', models.FloatField(default=0.0, help_text='Цена продукта')),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания продукта')),
                ('changed_at', models.DateTimeField(auto_now=True, help_text='Время изменения продукта')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя тэга', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Описание тэга', max_length=1024)),
                ('product', models.ManyToManyField(to='routing.product')),
            ],
            options={
                'verbose_name': 'Тэги',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.DeleteModel(
            name='Chocolate',
        ),
        migrations.AddField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order_positions', through='routing.OrderPosition', to='routing.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.product'),
        ),
    ]
