# Generated by Django 4.2.6 on 2023-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_alter_category_id_alter_orderposition_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Позиции заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='flowers_images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Имя продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена продукта'),
        ),
    ]
