# Generated by Django 4.2.6 on 2023-11-21 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_alter_orderposition_options_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Описание категории', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Имя категории', max_length=255, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания модели', verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_address',
            field=models.CharField(help_text='Адрес доставки заказа', max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(error_messages='Номер телефона не является российским номером или же неправильно набран', max_length=11, validators=[django.core.validators.RegexValidator(regex='^((\\7|8)+([0-9]){10})$')], verbose_name='Номер телефона'),
        ),
    ]
