# Generated by Django 4.2.6 on 2023-12-14 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routing.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(error_messages='Номер телефона не является российским номером или же неправильно набран', max_length=11, validators=[django.core.validators.RegexValidator(regex='^((7|8)+([0-9]){10})$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='discount_per_single_product',
            field=models.FloatField(default=0.0, help_text='Скидка за единицу товара', verbose_name='Скидка за единицу товара'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='quantity_of_products',
            field=models.PositiveIntegerField(default=0, help_text='Количество позиций в заказе', verbose_name='Количество продуктов'),
        ),
    ]
