# Generated by Django 4.2.6 on 2023-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_remove_category_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(to='routing.tag'),
        ),
    ]
