# Generated by Django 4.2.6 on 2023-12-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_remove_tag_product_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='tag',
        ),
    ]
