# Generated by Django 4.2.6 on 2023-12-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_order_order_id_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
